# Anthropic API Configuration
anthropic:
  api_key_env_var: ANTHROPIC_API_KEY

# Model Configuration
model:
  name: claude-3-sonnet-20240229
  max_tokens: 300
  temperature: 0.7

# Tool Configuration
tools:
  real_quotes:
    search_url: https://www.goodreads.com/author/quotes/3371.Dave_Eggers

# Fake Quote Generation
fake_quotes:
  min_year: 2000
  max_year: 2023